### ISSUE TITLE
Error when drag parent node to child node (data list is empty)

### ISSUE THREAD

**Issue by eclipse2110** [shuiRong/vue-drag-tree-demo#3]

**Comment by shuiRong** [comment]
Thanks for reporting.
It's a bug, I'll fixed it soon

**Comment by shuiRong** [comment]
> Thanks for reporting.
> It's a bug, I'll fixed it soon

@vudangdo2  I fixed it just now. 
The latest version of `vue-drag-tree` is `1.1.5`. 
You need to modify it in `package.json` or reclone `vue-drag-tree-demo` project.

**Comment by eclipse2110** [comment]
Thanks
